### ISSUE TITLE
i put a good token from the discord site to the config and it still say it

### ISSUE THREAD

**Issue by alonalibarmn** [TheRealToxicDev/Toxic-Verifier#1]
![image](https://user-images.githubusercontent.com/71559074/97796553-ebc23480-1c1b-11eb-9e88-0a1f164069a8.png)

**Comment by alonalibarmn** [comment]
how i fix it?

**Comment by CodeMeAPixel** [comment]
If you are hosting this from console which it looks like you are then the easier option is to just go to the bots main file `verify.js` and find the line `client.login()`

Replace it with

`client.login(“Token_Here”)`

**Comment by CodeMeAPixel** [comment]
It’s most likely throwing that error cause I have it set to read token from process.env so just replace that

**Comment by alonalibarmn** [comment]
![image](https://user-images.githubusercontent.com/71559074/97809736-771ce380-1c77-11eb-9074-932fb9b1c50e.png)
this one?

**Comment by CodeMeAPixel** [comment]
Yup

**Comment by alonalibarmn** [comment]
ok now its work how do i verify ?

**Comment by alonalibarmn** [comment]
?

**Comment by CodeMeAPixel** [comment]
https://github.com/TheRealToxicDev/Toxic-Verifier#configuration

**Comment by CodeMeAPixel** [comment]
If all that is setup then the rest is automatic, people join bot DMs them a code they have to enter in the channel

**Comment by alonalibarmn** [comment]
i did everithing i joind and its not sending dm

**Comment by CodeMeAPixel** [comment]
Errors?

**Comment by alonalibarmn** [comment]
no thare is no errors

**Comment by CodeMeAPixel** [comment]
Alright I’ll look into the issue and post an update soon

**Comment by CodeMeAPixel** [comment]
@alonalibarmn make sure you have intents enabled in the DEV PORTAL
![04A9420E-4DF7-4B33-A3F2-5733866C6A36](https://user-images.githubusercontent.com/59587139/99308519-4dd28a80-2815-11eb-85ef-a4ada5dbf801.jpeg)

**Comment by TheRealToxicDev** [comment]
#d859f12
